### ISSUE TITLE
Is `next export` supported?

### ISSUE THREAD

**Issue by adammockor** [vercel/next-react-server-components#1]
I tried to add `next export` to `package.json` like so `"build": "yarn next build && yarn next export"`, but non of the pages (other then 404) is generated. Why so? Not even when I add `getStaticProps` to some pages, like `index.js`, `csr.js` or `rsc.server.js`.

**Comment by leerob** [comment]
Hey all! `next export` support is planned for the `app` directory, but is not implemented. We won't be adding `next export` to this demo specifically, but will be talking more about this once support has landed. You can view the roadmap here: https://beta.nextjs.org/docs/app-directory-roadmap
