### ISSUE TITLE
Not working with React 18 rc.1

### ISSUE THREAD

**Issue by demiluke** [vercel/next-react-server-components#32]
We are evaluating server components in our app.  While attempting to get it to work, I kept getting the following error.  I  decided to try this simple example.  Initially it works without issue, however if you update react to RC 1 (what our app is on), you get the same error we experience.

![image](https://user-images.githubusercontent.com/100597914/156777657-beddf3cc-0090-47fa-b4a5-2cfc3c172785.png)

**Comment by huozhi** [comment]
The 18 rc1 support is added in https://github.com/vercel/next.js/pull/34972 , please wait for the incomg canary release to integrate with it since there's few breaking changes bewteen rc0 and rc1 for streaming part
