### ISSUE TITLE
The SSR + Api delay example is broken

### ISSUE THREAD

**Issue by ReangeloJ** [vercel/next-react-server-components#4]
Hey 
The ssr + api delay example is broken. I get an error 500 on:
https://next-news-rsc.vercel.sh/ssr

Thanks in advance! :)

![image](https://user-images.githubusercontent.com/25207023/139216482-88626ca5-5d7d-4823-9c07-56400fcf4958.png)

**Comment by SoraKumo001** [comment]
Vercel's specification seems to cause an error if the SSR process exceeds 1.5 seconds.
As a workaround, I created a hybrid SSR-Streaming process.

https://next-streaming.vercel.app/ssr-slow
https://github.com/SoraKumo001/next-streaming

It performs static SSR within the limit of 1.4 seconds, and switches to SSR-Streaming when it times out.

**Comment by leerob** [comment]
This should be resolved, but please let me know if you see it not working 😄
