### ISSUE TITLE
Server components are broken with Next v.12.2.1

### ISSUE THREAD

**Issue by neatbyte-vnobis** [vercel/next-react-server-components#51]
**Steps to Reproduce:**

1. Clone the repository
2. Run locally
3. Go to /slow or /rsc
4. Pages won`t render (infinite loading)

**Fix:**
After downgrading to Next  v.12.1.* (currently 12.1.6) everything works as expected

Updated package.json:
```
{
  "scripts": {
    "dev": "yarn next dev",
    "build": "yarn next build",
    "start": "yarn next start"
  },
  "dependencies": {
    "ms": "2.1.3",
    "next": "12.1.*",
    "react": "^18.1.0",
    "react-dom": "^18.1.0"
  }
}
```

**Comment by minhchu** [comment]
I'm having the same issue with Next 12.2.1

**Comment by leerob** [comment]
Hey folks! I would recommend not using this just yet while we work on moving toward the [Layouts RFC](https://nextjs.org/blog/layouts-rfc), which uses Server Components by default.

**Comment by leerob** [comment]
Refactored to v13 and `app`: https://github.com/vercel/next-react-server-components/pull/53
