### ISSUE TITLE
Server dependency is being included in the frontend bundle

### ISSUE THREAD

**Issue by fredcido** [vercel/next-react-server-components#52]
Hey all,  first of all thank you for the interesting demo.

It seems that the demo is quite not fulfilling one of the main purposes of RSC, which is to keep server dependency in the server.

Example:

```typescript
// ./components/Time.server.js

import moment from "moment";

const Time = () => {
  return <p>{moment().format("DD/MM/yyyy H:mm")}</p>;
};

export default Time;
```

```typescript
// ./pages/index.js 

import { Suspense } from "react";
import Time from "../components/Time.server";

export default function Index() {
  return (
    <Suspense fallback={"Loading..."}>
      <Time />
    </Suspense>
  );
}
```

The `moment` dependency is being included into the client bundle, checked the chunks into `.next/static` folder and also with `@next/bundle-analyzer`:

<img width="1625" alt="image" src="https://user-images.githubusercontent.com/7162412/189213207-0c947956-7393-4e75-a9db-e945015ce79c.png">

**Comment by bishopwm** [comment]
I'm seeing this as well. 

Maybe you have some insights Vercel team? 😄 @huozhi @shuding @leerob

**Comment by leerob** [comment]
Hey there! We do not recommend profiling the repository right now, as there _will_ be bugs, and we're switching the architecture as we move towards the work defined in the [Layouts RFC](https://nextjs.org/blog/layouts-rfc), which uses Server Components by default.
