### ISSUE TITLE
Routing with nextjs ?

### ISSUE THREAD

**Issue by revskill10** [vercel/next-react-server-components#6]
Thanks for great demo!

One question related to routing, currently it seems impossible to read queryparams in server component.

Do you have any example/guideline for that?

**Comment by shuding** [comment]
Yeah, currently React Context isn’t implemented in RSC so we can’t use `useRouter` in server components. As a **temporary** workaround, `router` is passed to the page as a prop (same as the `withRouter` behavior).

But this is just a temporary workaround and RSC is still an experimental thing, this will change in future updates.

**Comment by revskill10** [comment]
@shuding I tried to use `withRouter` for main component but got error 

```
Error: This Hook is not supported in Server Components.
```

Do you have any guideline for it ?

**Comment by shuding** [comment]
@revskill10 It's already there, you don't need to wrap it with `withRouter`:

```js
export default function Page({ router }) {
  ...
}
```

Also keep in mind that this router object only has `query`, `route` and `asPath` fields...

**Comment by revskill10** [comment]
@shuding I tried with this, one concern is, i have to check if `router` is defined first, else return null at first render.

**Comment by carlosagsmendes** [comment]
> Also keep in mind that this router object only has `query`, `route` and `asPath` fields...

Thanks for the clarification. But the plans are to get back access to the context in the page, right?

**Comment by leerob** [comment]
This is now supported: https://github.com/vercel/next-react-server-components/blob/main/app/item/page.js#L9-L12

https://beta.nextjs.org/docs/api-reference/file-conventions/page
